from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MyTicketEdit(QtWidgets.QWidget):
    def __init__(self):
        super(Ui_MyTicketEdit, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1112, 763)
        self.setStyleSheet("background-color: #1a1a1a;\n"
"color: #e7e7e5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout = QtWidgets.QWidget(parent=self)
        self.layout.setMaximumSize(QtCore.QSize(1094, 16777215))
        self.layout.setStyleSheet("QWidget {\n"
"background-color: #202122;\n"
"}\n"
"\n"
"QTextEdit {\n"
"border: 1px solid #353738;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"border: 1px solid #dc5049;\n"
"}\n"
"\n"
"QComboBox {\n"
"border: 1px solid #353738;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"border: 1px solid #dc5049;\n"
"}")
        self.layout.setObjectName("layout")
        self.tableView = QtWidgets.QTableView(parent=self.layout)
        self.tableView.setGeometry(QtCore.QRect(0, 260, 1090, 251))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 80, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 80, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.tableView.setPalette(palette)
        self.tableView.setStyleSheet("border: 1px solid #353738")
        self.tableView.setObjectName("tableView")
        self.topBar = QtWidgets.QWidget(parent=self.layout)
        self.topBar.setGeometry(QtCore.QRect(9, 9, 1094, 241))
        self.topBar.setMinimumSize(QtCore.QSize(0, 200))
        self.topBar.setObjectName("topBar")
        self.titleLabelForTicket = QtWidgets.QLabel(parent=self.topBar)
        self.titleLabelForTicket.setGeometry(QtCore.QRect(190, 30, 161, 21))
        font = QtGui.QFont()
        font.setBold(False)
        self.titleLabelForTicket.setFont(font)
        self.titleLabelForTicket.setStyleSheet("color: #a5a7aa;")
        self.titleLabelForTicket.setWordWrap(True)
        self.titleLabelForTicket.setObjectName("titleLabelForTicket")
        self.titleEditForTicket = QtWidgets.QTextEdit(parent=self.topBar)
        self.titleEditForTicket.setGeometry(QtCore.QRect(190, 60, 251, 71))
        self.titleEditForTicket.setStyleSheet("")
        self.titleEditForTicket.setObjectName("titleEditForTicket")
        self.title = QtWidgets.QLabel(parent=self.topBar)
        self.title.setGeometry(QtCore.QRect(30, 20, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.title.setFont(font)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.descLabel = QtWidgets.QLabel(parent=self.topBar)
        self.descLabel.setGeometry(QtCore.QRect(480, 30, 161, 21))
        font = QtGui.QFont()
        font.setBold(False)
        self.descLabel.setFont(font)
        self.descLabel.setStyleSheet("color: #a5a7aa;")
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName("descLabel")
        self.descEdit = QtWidgets.QTextEdit(parent=self.topBar)
        self.descEdit.setGeometry(QtCore.QRect(480, 60, 531, 71))
        self.descEdit.setStyleSheet("")
        self.descEdit.setObjectName("descEdit")
        self.updateTicketButton = QtWidgets.QCommandLinkButton(parent=self.topBar)
        self.updateTicketButton.setGeometry(QtCore.QRect(890, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateTicketButton.setFont(font)
        self.updateTicketButton.setStyleSheet("QCommandLinkButton {\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"background-color: #dc5049;\n"
"}")
        self.updateTicketButton.setDescription("")
        self.updateTicketButton.setObjectName("updateTicketButton")
        self.title_2 = QtWidgets.QLabel(parent=self.topBar)
        self.title_2.setGeometry(QtCore.QRect(30, 200, 221, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.title_2.setFont(font)
        self.title_2.setWordWrap(True)
        self.title_2.setObjectName("title_2")
        self.titleLabelForComments = QtWidgets.QLabel(parent=self.layout)
        self.titleLabelForComments.setGeometry(QtCore.QRect(200, 580, 161, 21))
        font = QtGui.QFont()
        font.setBold(False)
        self.titleLabelForComments.setFont(font)
        self.titleLabelForComments.setStyleSheet("color: #a5a7aa;")
        self.titleLabelForComments.setWordWrap(True)
        self.titleLabelForComments.setObjectName("titleLabelForComments")
        self.titleEditForComments = QtWidgets.QTextEdit(parent=self.layout)
        self.titleEditForComments.setGeometry(QtCore.QRect(200, 610, 821, 71))
        self.titleEditForComments.setStyleSheet("")
        self.titleEditForComments.setObjectName("titleEditForComments")
        self.title_3 = QtWidgets.QLabel(parent=self.layout)
        self.title_3.setGeometry(QtCore.QRect(40, 520, 381, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.title_3.setFont(font)
        self.title_3.setWordWrap(True)
        self.title_3.setObjectName("title_3")
        self.createCommentButton = QtWidgets.QCommandLinkButton(parent=self.layout)
        self.createCommentButton.setGeometry(QtCore.QRect(900, 700, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createCommentButton.setFont(font)
        self.createCommentButton.setStyleSheet("QCommandLinkButton {\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"background-color: #dc5049;\n"
"}")
        self.createCommentButton.setDescription("")
        self.createCommentButton.setObjectName("createCommentButton")
        self.horizontalLayout.addWidget(self.layout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.titleLabelForTicket.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.titleLabelForTicket.setText(_translate("Form", "<html><head/><body><p>Загаловок</p></body></html>"))
        self.title.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.title.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt;\">Заявка:</span></p></body></html>"))
        self.descLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.descLabel.setText(_translate("Form", "<html><head/><body><p>Описание</p></body></html>"))
        self.updateTicketButton.setText(_translate("Form", "Обновить"))
        self.title_2.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.title_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt;\">Комментарии:</span></p></body></html>"))
        self.titleLabelForComments.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.titleLabelForComments.setText(_translate("Form", "<html><head/><body><p>Загаловок</p></body></html>"))
        self.title_3.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.title_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt;\">Добавить комментарий:</span></p></body></html>"))
        self.createCommentButton.setText(_translate("Form", "Добавить"))

