from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Users(QtWidgets.QWidget):
    def __init__(self):
        super(Ui_Users, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1112, 763)
        self.setStyleSheet("background-color: #1a1a1a;\n"
"color: #e7e7e5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout = QtWidgets.QWidget(parent=self)
        self.layout.setMaximumSize(QtCore.QSize(1094, 16777215))
        self.layout.setStyleSheet("QWidget {\n"
"background-color: #202122;\n"
"}\n"
"\n"
"QTextEdit {\n"
"border: 1px solid #353738;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"border: 1px solid #dc5049;\n"
"}\n"
"\n"
"QComboBox {\n"
"border: 1px solid #353738;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"border: 1px solid #dc5049;\n"
"}")
        self.layout.setObjectName("layout")
        self.title = QtWidgets.QLabel(parent=self.layout)
        self.title.setGeometry(QtCore.QRect(40, 30, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.layout)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 1091, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_users = QtWidgets.QWidget()
        self.tab_users.setObjectName("tab_users")
        self.tableView = QtWidgets.QTableView(parent=self.tab_users)
        self.tableView.setGeometry(QtCore.QRect(0, 110, 1090, 521))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 80, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 80, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.tableView.setPalette(palette)
        self.tableView.setStyleSheet("border: 1px solid #353738")
        self.tableView.setObjectName("tableView")
        self.searchLabel = QtWidgets.QLabel(parent=self.tab_users)
        self.searchLabel.setGeometry(QtCore.QRect(10, 20, 351, 21))
        font = QtGui.QFont()
        font.setBold(False)
        self.searchLabel.setFont(font)
        self.searchLabel.setStyleSheet("color: #a5a7aa;")
        self.searchLabel.setWordWrap(True)
        self.searchLabel.setObjectName("searchLabel")
        self.searchEdit = QtWidgets.QTextEdit(parent=self.tab_users)
        self.searchEdit.setGeometry(QtCore.QRect(10, 50, 261, 31))
        self.searchEdit.setStyleSheet("")
        self.searchEdit.setObjectName("searchEdit")
        self.searchButton = QtWidgets.QCommandLinkButton(parent=self.tab_users)
        self.searchButton.setGeometry(QtCore.QRect(290, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("QCommandLinkButton {\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"background-color: #dc5049;\n"
"}")
        self.searchButton.setDescription("")
        self.searchButton.setObjectName("searchButton")
        self.tabWidget.addTab(self.tab_users, "")
        self.tab_create_user = QtWidgets.QWidget()
        self.tab_create_user.setObjectName("tab_create_user")
        self.loginLabel = QtWidgets.QLabel(parent=self.tab_create_user)
        self.loginLabel.setGeometry(QtCore.QRect(210, 100, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: #a5a7aa;")
        self.loginLabel.setWordWrap(True)
        self.loginLabel.setObjectName("loginLabel")
        self.firstNameLabel = QtWidgets.QLabel(parent=self.tab_create_user)
        self.firstNameLabel.setGeometry(QtCore.QRect(560, 100, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        self.firstNameLabel.setFont(font)
        self.firstNameLabel.setStyleSheet("color: #a5a7aa;")
        self.firstNameLabel.setWordWrap(True)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.lastNameLabel = QtWidgets.QLabel(parent=self.tab_create_user)
        self.lastNameLabel.setGeometry(QtCore.QRect(560, 170, 61, 21))
        font = QtGui.QFont()
        font.setBold(False)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setStyleSheet("color: #a5a7aa;")
        self.lastNameLabel.setWordWrap(True)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.loginEdit = QtWidgets.QTextEdit(parent=self.tab_create_user)
        self.loginEdit.setGeometry(QtCore.QRect(210, 120, 301, 31))
        self.loginEdit.setStyleSheet("")
        self.loginEdit.setObjectName("loginEdit")
        self.phoneNumberEdit = QtWidgets.QTextEdit(parent=self.tab_create_user)
        self.phoneNumberEdit.setGeometry(QtCore.QRect(560, 250, 301, 31))
        self.phoneNumberEdit.setStyleSheet("")
        self.phoneNumberEdit.setObjectName("phoneNumberEdit")
        self.passwordEdit = QtWidgets.QTextEdit(parent=self.tab_create_user)
        self.passwordEdit.setGeometry(QtCore.QRect(210, 190, 301, 31))
        self.passwordEdit.setStyleSheet("")
        self.passwordEdit.setObjectName("passwordEdit")
        self.passwodLabel = QtWidgets.QLabel(parent=self.tab_create_user)
        self.passwodLabel.setGeometry(QtCore.QRect(210, 170, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.passwodLabel.setFont(font)
        self.passwodLabel.setStyleSheet("color: #a5a7aa;")
        self.passwodLabel.setWordWrap(True)
        self.passwodLabel.setObjectName("passwodLabel")
        self.phoneNumberLabel = QtWidgets.QLabel(parent=self.tab_create_user)
        self.phoneNumberLabel.setGeometry(QtCore.QRect(560, 230, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.phoneNumberLabel.setFont(font)
        self.phoneNumberLabel.setStyleSheet("color: #a5a7aa;")
        self.phoneNumberLabel.setWordWrap(True)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.lastNameEdit = QtWidgets.QTextEdit(parent=self.tab_create_user)
        self.lastNameEdit.setGeometry(QtCore.QRect(560, 190, 301, 31))
        self.lastNameEdit.setStyleSheet("")
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.firstNameEdit = QtWidgets.QTextEdit(parent=self.tab_create_user)
        self.firstNameEdit.setGeometry(QtCore.QRect(560, 120, 301, 31))
        self.firstNameEdit.setStyleSheet("")
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.rolesComboBox = QtWidgets.QComboBox(parent=self.tab_create_user)
        self.rolesComboBox.setGeometry(QtCore.QRect(210, 250, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 33, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 229, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.rolesComboBox.setPalette(palette)
        self.rolesComboBox.setObjectName("rolesComboBox")
        self.rolesLabel = QtWidgets.QLabel(parent=self.tab_create_user)
        self.rolesLabel.setGeometry(QtCore.QRect(210, 230, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.rolesLabel.setFont(font)
        self.rolesLabel.setStyleSheet("color: #a5a7aa;")
        self.rolesLabel.setWordWrap(True)
        self.rolesLabel.setObjectName("rolesLabel")
        self.createButton = QtWidgets.QCommandLinkButton(parent=self.tab_create_user)
        self.createButton.setGeometry(QtCore.QRect(480, 340, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("QCommandLinkButton {\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QCommandLinkButton:hover {\n"
"background-color: #dc5049;\n"
"}")
        self.createButton.setDescription("")
        self.createButton.setObjectName("createButton")
        self.tabWidget.addTab(self.tab_create_user, "")
        self.horizontalLayout.addWidget(self.layout)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.title.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.title.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt;\">Пользователи</span></p></body></html>"))
        self.searchLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.searchLabel.setText(_translate("Form", "<html><head/><body><p>Поиск по логину, имени и фамилии</p></body></html>"))
        self.searchButton.setText(_translate("Form", "Найти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_users), _translate("Form", "Просмотр"))
        self.loginLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.loginLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Логин</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.firstNameLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.firstNameLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Имя</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.lastNameLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.lastNameLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Фамилия</span></p></body></html>"))
        self.passwodLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.passwodLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Пароль</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.phoneNumberLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.phoneNumberLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Номер телефона</span></p></body></html>"))
        self.rolesLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Control System Work Tracker</span></p></body></html>"))
        self.rolesLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Роль</span></p></body></html>"))
        self.createButton.setText(_translate("Form", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_create_user), _translate("Form", "Добавить"))
